name: DisasterPlannig API

on:
  repository_dispatch:
    types: [api]

jobs:
  API:
    runs-on: ubuntu-latest
    name: Running API
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: launch Python
        run: python main.py $MESSAGE
        env:
         MESSAGE: ${{ github.event.client_payload.message }}