name: DisasterPlannig API

on:
  repository_dispatch:
    types: [api]

jobs:
  steps:
  - uses: actions/checkout@v3
  - uses: actions/setup-python@v4
    with:
      python-version: '3.10' 
    - env:
        MESSAGE: ${{ github.event.client_payload.message }}
      run: python main.py $MESSAGE